# Generated by Django 5.0.1 on 2024-01-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('people_amount', models.IntegerField()),
            ],
        ),
    ]
