# Generated by Django 5.0.1 on 2024-01-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_usersconnected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersconnected',
            old_name='room',
            new_name='room_code',
        ),
    ]
