# Generated by Django 5.0.1 on 2024-01-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_rename_room_usersconnected_room_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersConnected',
        ),
    ]
