# Generated by Django 5.0.1 on 2024-02-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_code',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
