# Generated by Django 5.0.1 on 2024-02-27 16:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_rename_admiteduser_banned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='banned',
            unique_together={('room', 'user')},
        ),
    ]
