# Generated by Django 5.0.1 on 2024-03-18 03:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_banned_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomIntances',
            new_name='RoomInstances',
        ),
    ]
